name: Test

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [16.x]
        os: [ubuntu-latest]

    env:
      CHROME_LINUX: ${{ secrets.CHROME_LINUX }}

    steps:
      - uses: actions/checkout@v2
      - name: Using Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest
      - name: Install dependencies
        run: yarn
      - name: Test
        run: yarn test
